"""
Debug why UI always shows 'not found'.
Traces exactly what the frontend sends and what the backend has.
"""
import sys
sys.stdout.reconfigure(encoding='utf-8')
import requests

BASE = 'http://localhost:8000'

# Simulate what the frontend does on first upload (no prior session_id)
# The ingest returns session_id=None → frontend generates its own "session_xxx"
print("="*60)
print("STEP 1: What does /ingest return when no session_id is sent?")
print("="*60)
import requests, time

# Test with no session_id (like the frontend's first upload)
resp = requests.post(f'{BASE}/ingest', files=[], data={})
print(f"Empty ingest returns: {resp.status_code} - {resp.text[:100]}")

# Now check what session_id the query endpoint receives from a typical browser session
print()
print("="*60)
print("STEP 2: Query with no session_id (null from frontend)")
print("="*60)
resp = requests.post(f'{BASE}/query', json={'question': 'What is multi-head attention?', 'session_id': None})
data = resp.json()
print(f"Status: {data.get('status')}")
print(f"Answer: {data.get('answer', data.get('message', ''))[:200]}")

print()
print("="*60)
print("STEP 3: Query with empty string session_id")
print("="*60)
resp = requests.post(f'{BASE}/query', json={'question': 'What is multi-head attention?', 'session_id': ''})
data = resp.json()
print(f"Status: {data.get('status')}")
print(f"Answer: {data.get('answer', data.get('message', ''))[:200]}")

print()
print("="*60)
print("STEP 4: Check what session_ids exist in the database")
print("="*60)

# Direct DB inspection
from app.shared.config import get_mongo_client, MONGODB_DB
mongo = get_mongo_client()
db = mongo[MONGODB_DB]
pipeline = [
    {"$group": {"_id": "$session_id", "count": {"$sum": 1}}},
    {"$sort": {"count": -1}},
    {"$limit": 10}
]
results = list(db['chunks'].aggregate(pipeline))
print("Session IDs in MongoDB chunks collection:")
for r in results:
    sid = repr(r['_id'])
    print(f"  session_id={sid}: {r['count']} chunks")

print()
print("="*60)
print("STEP 5: What does BM25 return for a typical browser session_id?")
print("="*60)
# Simulate the fake session_id generated by the frontend
fake_session = f"session_{int(time.time())}"
print(f"Using fake browser session: {fake_session!r}")
from app.query.bm25_retriever import bm25_search, invalidate_index
invalidate_index()
chunks = bm25_search("What is multi-head attention?", top_k=5, session_id=fake_session)
print(f"BM25 results for fake session: {len(chunks)}")

print()
print("Fallback: BM25 with session_id=None (global)")
chunks_global = bm25_search("What is multi-head attention?", top_k=5, session_id=None)
print(f"BM25 results global: {len(chunks_global)}")
